-- Run order (Supabase SQL Editor): 1) inmu_import.sql -> 2) catalog_cleanup.sql -> 3) food_search_names.sql -> 4) portion_setup_phase2.sql -> 5) add_doh_foods.sql -> 6) food_photos.sql
-- FitFast: food photos from Wikimedia Commons (free licences only).
-- Every photo was checked by eye to show the right dish. CC BY and CC BY-SA
-- require credit, so the app shows image_credit under the photo.
-- The link points at Wikimedia's own image server (hotlinking is allowed).
-- Run after catalog_cleanup.sql and add_doh_foods.sql. Safe to re-run.

alter table public.foods_catalog add column if not exists image_credit text;
alter table public.foods_catalog add column if not exists image_source_url text;

-- Photos copied from other websites without a licence are removed.
update public.foods_catalog
set image_url = null, image_credit = null, image_source_url = null
where image_url is not null
  and image_url not like 'https://upload.wikimedia.org/%'
  and image_url not like 'https://thumb.wikimedia.org/%';

with photos(food_code, image_url, image_credit, image_source_url) as (
  values
    ('T9', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/2/27/Pad_Thai_at_Kinn_Thai_Restaurant%2C_Canberra%2C_2022.jpg/500px-Pad_Thai_at_Kinn_Thai_Restaurant%2C_Canberra%2C_2022.jpg', 'ภาพ: Kgbo / CC BY-SA 4.0 / Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Pad_Thai_at_Kinn_Thai_Restaurant,_Canberra,_2022.jpg'),
    ('T12', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/1/18/Kuai-tiao_rat_na_mu.JPG/500px-Kuai-tiao_rat_na_mu.JPG', 'ภาพ: Takeaway / CC BY-SA 3.0 / Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Kuai-tiao_rat_na_mu.JPG'),
    ('T8', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a7/Guaytiew_Pad_Kee_Mao_%28Drunken_Noodles%29_with_Veg_%26_Tofu_-_Rosa%27s_Thai_2025-07-22.jpg/500px-Guaytiew_Pad_Kee_Mao_%28Drunken_Noodles%29_with_Veg_%26_Tofu_-_Rosa%27s_Thai_2025-07-22.jpg', 'ภาพ: Andy Li / CC0 / Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Guaytiew_Pad_Kee_Mao_(Drunken_Noodles)_with_Veg_%26_Tofu_-_Rosa%27s_Thai_2025-07-22.jpg'),
    ('T10', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/7/7e/Yen_Ta_Fo_Wat_Kaek_%28original%29.jpg/500px-Yen_Ta_Fo_Wat_Kaek_%28original%29.jpg', 'ภาพ: Phoebus 28 / CC BY 4.0 / Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Yen_Ta_Fo_Wat_Kaek_(original).jpg'),
    ('T310', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/c/cf/Khao_Soi_Northern_Thai_food_%E0%B8%82%E0%B9%89%E0%B8%B2%E0%B8%A7%E0%B8%8B%E0%B8%AD%E0%B8%A2_%E0%B8%9C%E0%B8%B1%E0%B8%81%E0%B8%94%E0%B8%AD%E0%B8%87.jpg/500px-Khao_Soi_Northern_Thai_food_%E0%B8%82%E0%B9%89%E0%B8%B2%E0%B8%A7%E0%B8%8B%E0%B8%AD%E0%B8%A2_%E0%B8%9C%E0%B8%B1%E0%B8%81%E0%B8%94%E0%B8%AD%E0%B8%87.jpg', 'ภาพ: Chainwit. / CC BY-SA 4.0 / Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Khao_Soi_Northern_Thai_food_%E0%B8%82%E0%B9%89%E0%B8%B2%E0%B8%A7%E0%B8%8B%E0%B8%AD%E0%B8%A2_%E0%B8%9C%E0%B8%B1%E0%B8%81%E0%B8%94%E0%B8%AD%E0%B8%87.jpg'),
    ('T177', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/8/8d/LK_Macau_Wonton_noodle_soup_09-05-2023.jpg/500px-LK_Macau_Wonton_noodle_soup_09-05-2023.jpg', 'ภาพ: LN9267 / CC BY-SA 4.0 / Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:LK_Macau_Wonton_noodle_soup_09-05-2023.jpg'),
    ('T54', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/6/69/2017_0426_Mu_krop_phat_kaphrao_khai_dao_rat_khao_in_Ayutthaya.jpg/500px-2017_0426_Mu_krop_phat_kaphrao_khai_dao_rat_khao_in_Ayutthaya.jpg', 'ภาพ: Takeaway / CC BY-SA 4.0 / Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:2017_0426_Mu_krop_phat_kaphrao_khai_dao_rat_khao_in_Ayutthaya.jpg'),
    ('T59', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/1/18/Khao_man_kai_CM.jpg/500px-Khao_man_kai_CM.jpg', 'ภาพ: Takeaway / CC BY-SA 3.0 / Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Khao_man_kai_CM.jpg'),
    ('T48', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/6/68/Khao_kha_mu_02.JPG/500px-Khao_kha_mu_02.JPG', 'ภาพ: Takeaway / CC BY-SA 3.0 / Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Khao_kha_mu_02.JPG'),
    ('T64', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/3/39/Khao_mu_daeng.jpg/500px-Khao_mu_daeng.jpg', 'ภาพ: Takeaway / CC BY-SA 3.0 / Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Khao_mu_daeng.jpg'),
    ('T56', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/7/74/Thai_Street_Fried_Rice_-_Thai_Street_Food%2C_Worthing_2026-08-21.jpg/500px-Thai_Street_Fried_Rice_-_Thai_Street_Food%2C_Worthing_2026-08-21.jpg', 'ภาพ: Andy Li / CC0 / Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Thai_Street_Fried_Rice_-_Thai_Street_Food,_Worthing_2026-08-21.jpg'),
    ('T51', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/0/05/Khao_tom_pla.jpg/500px-Khao_tom_pla.jpg', 'ภาพ: Takeaway / CC BY-SA 3.0 / Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Khao_tom_pla.jpg'),
    ('T184', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/b/bb/Thai_Green_Curry%2CJasminRice%2CChilli_Basil_Chicken_%2C_HomeMade.jpg/500px-Thai_Green_Curry%2CJasminRice%2CChilli_Basil_Chicken_%2C_HomeMade.jpg', 'ภาพ: PallaviKhale / CC BY-SA 4.0 / Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Thai_Green_Curry,JasminRice,Chilli_Basil_Chicken_,_HomeMade.jpg'),
    ('T188', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/0/0d/Panang_curry_%2842943883862%29.jpg/500px-Panang_curry_%2842943883862%29.jpg', 'ภาพ: Vee Satayamas from Bangkok, Thailand / CC BY 2.0 / Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Panang_curry_(42943883862).jpg'),
    ('T189', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/1/19/Chicken_Massaman_Curry_-Bangkok_-Food_%2830363542667%29.jpg/500px-Chicken_Massaman_Curry_-Bangkok_-Food_%2830363542667%29.jpg', 'ภาพ: Vee Satayamas from Bangkok, Thailand / CC BY 2.0 / Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Chicken_Massaman_Curry_-Bangkok_-Food_(30363542667).jpg'),
    ('T191', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/7/79/Kaeng_som-marum63.JPG/500px-Kaeng_som-marum63.JPG', 'ภาพ: Xufanc / CC BY-SA 3.0 / Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Kaeng_som-marum63.JPG'),
    ('T211', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/5/50/Tom_kha_kai_at_a_restaurant.jpg/500px-Tom_kha_kai_at_a_restaurant.jpg', 'ภาพ: Julia S. from USA / CC BY 2.0 / Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Tom_kha_kai_at_a_restaurant.jpg'),
    ('T212', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b4/Tom_yum_goong-01.jpg/500px-Tom_yum_goong-01.jpg', 'ภาพ: kisocci / CC BY-SA 2.0 / Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Tom_yum_goong-01.jpg'),
    ('T101', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/2/25/Larb_Moo_-_Siam_Thai_Restaurant_-_Regina_%2830194553768%29.jpg/500px-Larb_Moo_-_Siam_Thai_Restaurant_-_Regina_%2830194553768%29.jpg', 'ภาพ: Haydn Blackey from Cardiff, Wales / CC BY-SA 2.0 / Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Larb_Moo_-_Siam_Thai_Restaurant_-_Regina_(30194553768).jpg'),
    ('T128', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/8/81/Sai_krok_Isan_yai.jpg/500px-Sai_krok_Isan_yai.jpg', 'ภาพ: Takeaway / CC BY-SA 3.0 / Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Sai_krok_Isan_yai.jpg'),
    ('T214', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/e/ec/Thanin_market_tod_man_pla.jpg/500px-Thanin_market_tod_man_pla.jpg', 'ภาพ: Takeaway / CC BY-SA 3.0 / Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Thanin_market_tod_man_pla.jpg'),
    ('T133', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/d/da/DZ3_0635_Crispy_Thai-style_oyster_omelette_topped_with_fresh_scallions_-_a_savory_street-food_favorite_from_Sattahip.jpg/500px-DZ3_0635_Crispy_Thai-style_oyster_omelette_topped_with_fresh_scallions_-_a_savory_street-food_favorite_from_Sattahip.jpg', 'ภาพ: PattayaPatrol / CC BY-SA 4.0 / Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:DZ3_0635_Crispy_Thai-style_oyster_omelette_topped_with_fresh_scallions_-_a_savory_street-food_favorite_from_Sattahip.jpg'),
    ('T309', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/8/8e/Mu_sate.JPG/500px-Mu_sate.JPG', 'ภาพ: Takeaway / CC BY-SA 3.0 / Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Mu_sate.JPG'),
    ('T241', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/5/57/Prawn-and-pork-siu-mai.jpg/500px-Prawn-and-pork-siu-mai.jpg', 'ภาพ: Sara McCleary / CC BY-SA 4.0 / Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Prawn-and-pork-siu-mai.jpg'),
    ('T156', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/1/1e/Doujiang_and_youtiao_Taipei.jpg/500px-Doujiang_and_youtiao_Taipei.jpg', 'ภาพ: KQuhen / CC BY-SA 4.0 / Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Doujiang_and_youtiao_Taipei.jpg'),
    ('T249', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/2/2b/Bualoy_kaiwan_-_Thai_food.JPG/500px-Bualoy_kaiwan_-_Thai_food.JPG', 'ภาพ: User:Mattes / Public domain / Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Bualoy_kaiwan_-_Thai_food.JPG'),
    ('T319', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e4/David_enjoying_D%C3%B2uhu%C4%81.jpg/500px-David_enjoying_D%C3%B2uhu%C4%81.jpg', 'ภาพ: David / Public domain / Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:David_enjoying_D%C3%B2uhu%C4%81.jpg'),
    ('T318', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c5/SZ_%E6%B7%B1%E5%9C%B3_Shenzhen_%E7%A6%8F%E7%94%B0_Futian_%E4%B8%8A%E6%B2%99%E6%9D%91%E8%B7%AF_ShangShaCun_Road_%E9%BB%91%E8%89%B2%E6%B6%BC%E7%B2%89%E7%94%9C%E5%93%81_Grass_jelly_%E5%B0%8F%E8%B2%A9_food_stall_June_2024_R12S_01.jpg/500px-SZ_%E6%B7%B1%E5%9C%B3_Shenzhen_%E7%A6%8F%E7%94%B0_Futian_%E4%B8%8A%E6%B2%99%E6%9D%91%E8%B7%AF_ShangShaCun_Road_%E9%BB%91%E8%89%B2%E6%B6%BC%E7%B2%89%E7%94%9C%E5%93%81_Grass_jelly_%E5%B0%8F%E8%B2%A9_food_stall_June_2024_R12S_01.jpg', 'ภาพ: EYAMXAOLP / CC0 / Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:SZ_%E6%B7%B1%E5%9C%B3_Shenzhen_%E7%A6%8F%E7%94%B0_Futian_%E4%B8%8A%E6%B2%99%E6%9D%91%E8%B7%AF_ShangShaCun_Road_%E9%BB%91%E8%89%B2%E6%B6%BC%E7%B2%89%E7%94%9C%E5%93%81_Grass_jelly_%E5%B0%8F%E8%B2%A9_food_stall_June_2024_R12S_01.jpg'),
    ('T37', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/0/03/Khanom_chin_nam_ngiao.jpg/500px-Khanom_chin_nam_ngiao.jpg', 'ภาพ: Takeaway / CC BY-SA 3.0 / Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Khanom_chin_nam_ngiao.jpg'),
    ('T230', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/2/26/Liat_Portal_for_Foodie_Disorder_-_Spaghetti_bolognese_with_peas.jpg/500px-Liat_Portal_for_Foodie_Disorder_-_Spaghetti_bolognese_with_peas.jpg', 'ภาพ: HaJunkiyada / CC BY-SA 4.0 / Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Liat_Portal_for_Foodie_Disorder_-_Spaghetti_bolognese_with_peas.jpg'),
    ('T383', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/8/8b/Transparent_Slice_of_Sara_Lee_white_whole_grain_bread_in_the_Franklin_Farm_section_of_Oak_Hill%2C_Fairfax_County%2C_Virginia.png/500px-Transparent_Slice_of_Sara_Lee_white_whole_grain_bread_in_the_Franklin_Farm_section_of_Oak_Hill%2C_Fairfax_County%2C_Virginia.png', 'ภาพ: User:Famartin / CC BY-SA 4.0 / Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Transparent_Slice_of_Sara_Lee_white_whole_grain_bread_in_the_Franklin_Farm_section_of_Oak_Hill,_Fairfax_County,_Virginia.png'),
    ('A67', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a0/HK_food_cooking_%E8%BE%B2%E5%BF%83%E9%9D%9E%E6%B2%B9%E7%82%B8%E8%BE%9B%E6%8B%89%E9%BA%B5_Nongshim_Korean_%E8%BE%9B%E8%BE%A3%E5%8D%B3%E9%A3%9F%E9%BA%B5_Instant_Noodle_August_2026_N13P_10.jpg/500px-HK_food_cooking_%E8%BE%B2%E5%BF%83%E9%9D%9E%E6%B2%B9%E7%82%B8%E8%BE%9B%E6%8B%89%E9%BA%B5_Nongshim_Korean_%E8%BE%9B%E8%BE%A3%E5%8D%B3%E9%A3%9F%E9%BA%B5_Instant_Noodle_August_2026_N13P_10.jpg', 'ภาพ: LIEMN PorkwE MAO / CC0 / Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:HK_food_cooking_%E8%BE%B2%E5%BF%83%E9%9D%9E%E6%B2%B9%E7%82%B8%E8%BE%9B%E6%8B%89%E9%BA%B5_Nongshim_Korean_%E8%BE%9B%E8%BE%A3%E5%8D%B3%E9%A3%9F%E9%BA%B5_Instant_Noodle_August_2026_N13P_10.jpg'),
    ('F162', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/3/32/Khao_mu_krop.jpg/500px-Khao_mu_krop.jpg', 'ภาพ: Takeaway / CC BY-SA 3.0 / Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Khao_mu_krop.jpg'),
    ('F56', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/e/ed/Sai_ua_CR.jpg/500px-Sai_ua_CR.jpg', 'ภาพ: Takeaway / CC BY-SA 3.0 / Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Sai_ua_CR.jpg'),
    ('F117', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/e/ee/Roast_duck_-_Bangkok_-_2017-05-12_%28001%29.jpg/500px-Roast_duck_-_Bangkok_-_2017-05-12_%28001%29.jpg', 'ภาพ: Iudexvivorum / CC0 / Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Roast_duck_-_Bangkok_-_2017-05-12_(001).jpg'),
    ('S37', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/1/19/Cajun_fries_from_Popeyes_Louisiana_Kitchen%2C_Stratford%2C_Ontario%2C_2025-08-04.jpg/500px-Cajun_fries_from_Popeyes_Louisiana_Kitchen%2C_Stratford%2C_Ontario%2C_2025-08-04.jpg', 'ภาพ: Chris Woodrich / CC BY-SA 4.0 / Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Cajun_fries_from_Popeyes_Louisiana_Kitchen,_Stratford,_Ontario,_2025-08-04.jpg'),
    ('S34', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/f/fe/Chicken_burger_in_healthy_bites.jpg/500px-Chicken_burger_in_healthy_bites.jpg', 'ภาพ: Medhi jyoti / CC BY 4.0 / Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Chicken_burger_in_healthy_bites.jpg'),
    ('S31', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/5/52/Super_Supreme_Pizza%2C_Pizza_Hut_Perth%2C_2026_%2801%29.jpg/500px-Super_Supreme_Pizza%2C_Pizza_Hut_Perth%2C_2026_%2801%29.jpg', 'ภาพ: Bahnfrend / CC BY-SA 4.0 / Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Super_Supreme_Pizza,_Pizza_Hut_Perth,_2026_(01).jpg'),
    ('S32', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/5/54/Roti_Canai_%284553382259%29.jpg/500px-Roti_Canai_%284553382259%29.jpg', 'ภาพ: Geoff Peters from Vancouver, BC, Canada / CC BY 2.0 / Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Roti_Canai_(4553382259).jpg'),
    ('S38', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d7/Hot_dog_with_homemade_hot_dog_bun.jpg/500px-Hot_dog_with_homemade_hot_dog_bun.jpg', 'ภาพ: jeffreyw / CC BY 2.0 / Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Hot_dog_with_homemade_hot_dog_bun.jpg'),
    ('Q27', 'https://upload.wikimedia.org/wikipedia/commons/8/87/Food_-_Orange_juice_--_Smart-Servier.png', 'ภาพ: Laboratoires Servier / CC BY-SA 3.0 / Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Food_-_Orange_juice_--_Smart-Servier.png'),
    ('Q20', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/5/5b/Coconut_water_at_restaurant_in_Ko_Samui.jpg/500px-Coconut_water_at_restaurant_in_Ko_Samui.jpg', 'ภาพ: Superraptor123 / CC BY-SA 4.0 / Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Coconut_water_at_restaurant_in_Ko_Samui.jpg'),
    ('E74', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/a/ab/Ripe_Mango_%284477570032%29.jpg/500px-Ripe_Mango_%284477570032%29.jpg', 'ภาพ: Vegan Feast Catering / CC BY 2.0 / Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Ripe_Mango_(4477570032).jpg'),
    ('E98', 'https://upload.wikimedia.org/wikipedia/commons/5/53/Frutos_Ex%C3%B3ticos-LONGAN.jpg', 'ภาพ: Surukuku (Nelson Ramos-Lopes) / Public domain / Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Frutos_Ex%C3%B3ticos-LONGAN.jpg'),
    ('E17', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/1/12/Rambutan_%2854531836095%29.jpg/500px-Rambutan_%2854531836095%29.jpg', 'ภาพ: Choo Yut Shing / CC BY 2.0 / Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Rambutan_(54531836095).jpg'),
    ('E32', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/2/2f/DSCF0613_Spiky_durian_fruits_displayed_on_a_market_stall_ready_to_be_cut_and_served.jpg/500px-DSCF0613_Spiky_durian_fruits_displayed_on_a_market_stall_ready_to_be_cut_and_served.jpg', 'ภาพ: PattayaPatrol / CC BY-SA 4.0 / Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:DSCF0613_Spiky_durian_fruits_displayed_on_a_market_stall_ready_to_be_cut_and_served.jpg'),
    ('E114', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e3/Oranges_-_whole-halved-segment.jpg/500px-Oranges_-_whole-halved-segment.jpg', 'ภาพ: Ivar Leidus / CC BY-SA 4.0 / Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Oranges_-_whole-halved-segment.jpg'),
    ('E81', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/d/de/Peeled_diced_pawpaw.jpg/500px-Peeled_diced_pawpaw.jpg', 'ภาพ: Bukky658 / CC BY-SA 4.0 / Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Peeled_diced_pawpaw.jpg'),
    ('E104', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/5/5f/Litchi_chinensis190714mx.jpg/500px-Litchi_chinensis190714mx.jpg', 'ภาพ: Carlos Valenzuela / CC BY-SA 4.0 / Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Litchi_chinensis190714mx.jpg'),
    ('DOH14011', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/0/02/Fried_egg%2C_sunny_side_up.jpg/500px-Fried_egg%2C_sunny_side_up.jpg', 'ภาพ: David Benbennick / Public domain / Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Fried_egg,_sunny_side_up.jpg'),
    ('DOH14057', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b3/Thai_iced_tea_%285741022036%29.jpg/500px-Thai_iced_tea_%285741022036%29.jpg', 'ภาพ: Neil Conway from Oakland, USA / CC BY 2.0 / Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Thai_iced_tea_(5741022036).jpg'),
    ('DOH14050', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c4/Iced_latte%2C_Camel%27s_Joint_%40Fort%2C_Mombasa%2C_2025_%2801%29.jpg/500px-Iced_latte%2C_Camel%27s_Joint_%40Fort%2C_Mombasa%2C_2025_%2801%29.jpg', 'ภาพ: Bahnfrend / CC BY-SA 4.0 / Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Iced_latte,_Camel%27s_Joint_@Fort,_Mombasa,_2025_(01).jpg'),
    ('DOH14005', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/4/4d/Drumstick_chicken.JPG/500px-Drumstick_chicken.JPG', 'ภาพ: BrokenSphere / CC BY-SA 3.0 / Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Drumstick_chicken.JPG'),
    ('DOH11043', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c5/Khao_khluk_kapi_%2831137282118%29.jpg/500px-Khao_khluk_kapi_%2831137282118%29.jpg', 'ภาพ: Vee Satayamas from Bangkok, Thailand / CC BY 2.0 / Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Khao_khluk_kapi_(31137282118).jpg'),
    ('DOH14027', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e6/Doughnut_1.jpg/500px-Doughnut_1.jpg', 'ภาพ: Gaurav Dhwaj Khadka / CC BY-SA 4.0 / Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Doughnut_1.jpg'),
    ('DOH12043', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/1/1e/Croissant_In_Austria.jpg/500px-Croissant_In_Austria.jpg', 'ภาพ: בר / CC BY-SA 3.0 / Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Croissant_In_Austria.jpg'),
    ('DOH11111', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d0/Liat_Portal_for_Foodie_Disorder_-_Grilled_salmon_with_sweet_potatoes.jpg/500px-Liat_Portal_for_Foodie_Disorder_-_Grilled_salmon_with_sweet_potatoes.jpg', 'ภาพ: HaJunkiyada / CC BY-SA 4.0 / Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Liat_Portal_for_Foodie_Disorder_-_Grilled_salmon_with_sweet_potatoes.jpg'),
    ('DOH11092', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/2/26/Thai_suki%2C_Thai_hot_pot_preparation%2C_Dining_in_Bangkok%2C_Thailand.jpg/500px-Thai_suki%2C_Thai_hot_pot_preparation%2C_Dining_in_Bangkok%2C_Thailand.jpg', 'ภาพ: Vyacheslav Argenberg / CC BY 4.0 / Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Thai_suki,_Thai_hot_pot_preparation,_Dining_in_Bangkok,_Thailand.jpg'),
    ('DOH12030', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/5/55/Foi_thong.jpg/500px-Foi_thong.jpg', 'ภาพ: Takeaway / CC BY-SA 3.0 / Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Foi_thong.jpg')
)
update public.foods_catalog f
set image_url = p.image_url,
    image_credit = p.image_credit,
    image_source_url = p.image_source_url
from photos p
where f.food_code = p.food_code;

select food_code, coalesce(common_name_th, name_th) as name, image_credit
from public.foods_catalog
where image_url is not null
order by food_code;
