-- FitFast: verified Thai household serving units.
-- Run this file in Supabase SQL Editor after foods_catalog has been imported.

create table if not exists public.food_servings (
  id bigint generated by default as identity primary key,
  food_id bigint not null references public.foods_catalog(id) on delete cascade,
  label text not null,
  grams numeric not null check (grams > 0 and grams <= 5000),
  verified boolean not null default false,
  source_name text,
  source_url text,
  created_at timestamptz not null default now()
);

alter table public.food_servings add column if not exists verified boolean not null default false;
alter table public.food_servings add column if not exists source_name text;
alter table public.food_servings add column if not exists source_url text;
alter table public.food_servings enable row level security;

drop policy if exists "authenticated users can read verified servings" on public.food_servings;
create policy "authenticated users can read verified servings"
on public.food_servings for select
to authenticated
using (verified = true);

grant select on public.food_servings to authenticated;

-- ข้าวสวย 1 ทัพพี = 60 กรัม (กรมอนามัย)
update public.food_servings fs
set grams = 60,
    verified = true,
    source_name = 'กรมอนามัย กระทรวงสาธารณสุข',
    source_url = 'https://anamai.moph.go.th/th/news-anamai/38204'
from public.foods_catalog f
where fs.food_id = f.id
  and f.food_code in ('A11', 'A59')
  and fs.label = '1 ทัพพี';

insert into public.food_servings
  (food_id, label, grams, verified, source_name, source_url)
select f.id, '1 ทัพพี', 60, true,
       'กรมอนามัย กระทรวงสาธารณสุข',
       'https://anamai.moph.go.th/th/news-anamai/38204'
from public.foods_catalog f
where f.food_code in ('A11', 'A59')
  and not exists (
    select 1 from public.food_servings fs
    where fs.food_id = f.id and fs.label = '1 ทัพพี'
  );

-- เนื้อสัตว์ 1 ช้อนกินข้าว = 15 กรัม (กรมอนามัย)
-- จำกัดเฉพาะรายการที่ชื่อบ่งชี้ว่าเป็นเนื้อสัตว์ล้วน ไม่ใช้กับอาหารผสม/แกง/ผัด
insert into public.food_servings
  (food_id, label, grams, verified, source_name, source_url)
select f.id, '1 ช้อนกินข้าว', 15, true,
       'กรมอนามัย กระทรวงสาธารณสุข',
       'https://nutrition2.anamai.moph.go.th/th/book/download/?did=194287&id=46803&reload='
from public.foods_catalog f
where f.is_usable = true
  and (
    f.name_th ~ '^(เนื้อไก่|เนื้อหมู|เนื้อวัว|กุ้ง|ปลาหมึก|ตับหมู|เลือดหมู|ลูกชิ้นปลา)'
  )
  and f.name_th !~ '(แกง|ผัด|ทอด|ยำ|ลาบ|ส้มตำ|ก๋วยเตี๋ยว|ข้าว)'
  and not exists (
    select 1 from public.food_servings fs
    where fs.food_id = f.id and fs.label = '1 ช้อนกินข้าว'
  );

-- ตรวจผลหลังรัน
select fs.label, fs.grams, count(*) as food_count
from public.food_servings fs
where fs.verified = true
group by fs.label, fs.grams
order by fs.label;
